# See here for image contents: https://github.com/microsoft/vscode-dev-containers/tree/v0.191.1/containers/python-3/.devcontainer/base.Dockerfile

# [Choice] Python version: 3, 3.9, 3.8, 3.7, 3.6
ARG VARIANT="3.9"

FROM --platform="linux/amd64" mcr.microsoft.com/devcontainers/python:1-${VARIANT}-bullseye
